package trax;

import java.awt.Point;

/**
 * Station is a class that is used to hold the data for each rail station along the Trax lines, it implements comparable
 * ..in order to see if two stations on different lines with the same name are indeed the same station(i.e. 600 S on green
 * .. line is the same as 600 S on red line)
 * @author chrisdarnell Sawyer Reeve + Chris Darnell
 */
public class Station implements Comparable<Station>{
	
	private int ID;
	private String stationName;
	private RailLine line;
	private Point coordinates;
	private int x_coord;
	private int y_coord;
	
	/**
	 * Constructor
	 * @param id autogenerated ID number assigned to each station
	 * @param name name of each station taken in from a .txt file
	 * @param line the line each station is assigned to, (RGBF)
	 */
	public Station(int id, String name, RailLine line) {
		this.ID = id;
		this.stationName = name;
		this.line = line;
	}

	/**
	 * @return ID
	 */
	public int getID() {
		return ID;
	}

	/**
	 * @return stationName
	 */
	public String getStationName() {
		return stationName;
	}

	/**
	 * @return railLine
	 */
	public RailLine getRailLine() {
		return line;
	}

	/**
	 * setPoint sets the coordinates after being taken in from a provided txt file
	 * @param coord
	 */
	public void setPoint(Point coord) {
		coordinates = coord;
		this.x_coord = (int) coord.getX();
		this.y_coord = (int) coord.getY();
	}

	/**
	 * @return coordinates
	 */
	public Point getPoint() {
		return coordinates;
	}

	/**
	 * @return x coordinate
	 */
	public int getXcoord() {
		return x_coord;
	}

	/**
	 * @return y coordinate
	 */
	public int getYcoord() {
		return y_coord;
	}

	@Override
	public String toString() {
		return "ID:" + getID() + " | Line: " + line.getName() + " | " + stationName;
	}

	@Override
	public int compareTo(Station o) {
		return this.getStationName().compareTo(o.getStationName());
	}
	
	

}
